import 'package:student_manager/models/student.dart';

class StudentService {
  static List<Student> seedStudents() {
    return [
      Student(
        id: '1',
        name: 'Nguyễn Minh Anh',
        studentCode: 'SV2024001',
        className: 'CNTT-K18A',
        department: 'CNTT',
        major: 'Khoa học máy tính',
        course: 'K18',
        email: 'minhanh@univ.edu.vn',
        phone: '0901001001',
        address: 'Quận 1, TP.HCM',
        birthDate: DateTime(2004, 1, 14),
        gender: Gender.female,
        gpa: 3.82,
        avatarUrl: 'https://i.pravatar.cc/150?img=47',
      ),
      Student(
        id: '2',
        name: 'Trần Quốc Bảo',
        studentCode: 'SV2024002',
        className: 'QTKD-K18B',
        department: 'Kinh Tế',
        major: 'Quản trị kinh doanh',
        course: 'K18',
        email: 'quocbao@univ.edu.vn',
        phone: '0901001002',
        address: 'Thủ Đức, TP.HCM',
        birthDate: DateTime(2004, 2, 20),
        gender: Gender.male,
        gpa: 3.26,
        avatarUrl: 'https://i.pravatar.cc/150?img=12',
      ),
      Student(
        id: '3',
        name: 'Lê Thảo My',
        studentCode: 'SV2024003',
        className: 'CNTT-K18B',
        department: 'CNTT',
        major: 'Kỹ thuật phần mềm',
        course: 'K18',
        email: 'thaomy@univ.edu.vn',
        phone: '0901001003',
        address: 'Bình Thạnh, TP.HCM',
        birthDate: DateTime(2004, 5, 2),
        gender: Gender.female,
        gpa: 3.12,
      ),
      Student(
        id: '4',
        name: 'Phạm Gia Huy',
        studentCode: 'SV2024004',
        className: 'KTQT-K18A',
        department: 'Kinh Tế',
        major: 'Kinh tế quốc tế',
        course: 'K18',
        email: 'giahuy@univ.edu.vn',
        phone: '0901001004',
        address: 'Quận 7, TP.HCM',
        birthDate: DateTime(2004, 11, 9),
        gender: Gender.male,
        gpa: 2.76,
      ),
      Student(
        id: '5',
        name: 'Đỗ Quỳnh Trang',
        studentCode: 'SV2024005',
        className: 'CNTT-K18C',
        department: 'CNTT',
        major: 'Trí tuệ nhân tạo',
        course: 'K18',
        email: 'quynhtrang@univ.edu.vn',
        phone: '0901001005',
        address: 'Quận 10, TP.HCM',
        birthDate: DateTime(2004, 7, 23),
        gender: Gender.female,
        gpa: 3.67,
        avatarUrl: 'https://i.pravatar.cc/150?img=32',
      ),
      Student(
        id: '6',
        name: 'Vũ Đức Long',
        studentCode: 'SV2024006',
        className: 'QTKD-K18A',
        department: 'Kinh Tế',
        major: 'Marketing',
        course: 'K18',
        email: 'duclong@univ.edu.vn',
        phone: '0901001006',
        address: 'Tân Bình, TP.HCM',
        birthDate: DateTime(2004, 3, 18),
        gender: Gender.male,
        gpa: 2.34,
      ),
      Student(
        id: '7',
        name: 'Bùi Hải Nam',
        studentCode: 'SV2024007',
        className: 'CNTT-K19A',
        department: 'CNTT',
        major: 'An toàn thông tin',
        course: 'K19',
        email: 'hainam@univ.edu.vn',
        phone: '0901001007',
        address: 'Gò Vấp, TP.HCM',
        birthDate: DateTime(2005, 1, 12),
        gender: Gender.male,
        gpa: 3.94,
        avatarUrl: 'https://i.pravatar.cc/150?img=15',
      ),
      Student(
        id: '8',
        name: 'Ngô Thu Hà',
        studentCode: 'SV2024008',
        className: 'KTQT-K19B',
        department: 'Kinh Tế',
        major: 'Kinh doanh quốc tế',
        course: 'K19',
        email: 'thuha@univ.edu.vn',
        phone: '0901001008',
        address: 'Phú Nhuận, TP.HCM',
        birthDate: DateTime(2005, 4, 5),
        gender: Gender.female,
        gpa: 3.04,
      ),
      Student(
        id: '9',
        name: 'Hoàng Minh Khoa',
        studentCode: 'SV2024009',
        className: 'CNTT-K19B',
        department: 'CNTT',
        major: 'Hệ thống thông tin',
        course: 'K19',
        email: 'minhkhoa@univ.edu.vn',
        phone: '0901001009',
        address: 'Quận 3, TP.HCM',
        birthDate: DateTime(2005, 6, 29),
        gender: Gender.male,
        gpa: 2.62,
        avatarUrl: 'https://i.pravatar.cc/150?img=4',
      ),
      Student(
        id: '10',
        name: 'Tạ Khánh Linh',
        studentCode: 'SV2024010',
        className: 'QTKD-K19A',
        department: 'Kinh Tế',
        major: 'Tài chính doanh nghiệp',
        course: 'K19',
        email: 'khanhlinh@univ.edu.vn',
        phone: '0901001010',
        address: 'Quận 8, TP.HCM',
        birthDate: DateTime(2005, 8, 3),
        gender: Gender.female,
        gpa: 3.48,
      ),
      Student(
        id: '11',
        name: 'Phan Nhật Quang',
        studentCode: 'SV2024011',
        className: 'CNTT-K20A',
        department: 'CNTT',
        major: 'Kỹ thuật dữ liệu',
        course: 'K20',
        email: 'nhatquang@univ.edu.vn',
        phone: '0901001011',
        address: 'Bình Tân, TP.HCM',
        birthDate: DateTime(2006, 2, 11),
        gender: Gender.male,
        gpa: 3.22,
      ),
      Student(
        id: '12',
        name: 'Lý Ngọc Bích',
        studentCode: 'SV2024012',
        className: 'KTQT-K20A',
        department: 'Kinh Tế',
        major: 'Kế toán',
        course: 'K20',
        email: 'ngocbich@univ.edu.vn',
        phone: '0901001012',
        address: 'Quận 6, TP.HCM',
        birthDate: DateTime(2006, 1, 31),
        gender: Gender.female,
        gpa: 2.95,
        avatarUrl: 'https://i.pravatar.cc/150?img=29',
      ),
      Student(
        id: '13',
        name: 'Đinh Tiến Đạt',
        studentCode: 'SV2024013',
        className: 'CNTT-K20B',
        department: 'CNTT',
        major: 'Mạng máy tính',
        course: 'K20',
        email: 'tiendat@univ.edu.vn',
        phone: '0901001013',
        address: 'Tân Phú, TP.HCM',
        birthDate: DateTime(2006, 3, 25),
        gender: Gender.male,
        gpa: 3.58,
      ),
      Student(
        id: '14',
        name: 'Mai Hoài An',
        studentCode: 'SV2024014',
        className: 'QTKD-K20B',
        department: 'Kinh Tế',
        major: 'Thương mại điện tử',
        course: 'K20',
        email: 'hoaian@univ.edu.vn',
        phone: '0901001014',
        address: 'Nhà Bè, TP.HCM',
        birthDate: DateTime(2006, 7, 14),
        gender: Gender.female,
        gpa: 2.49,
      ),
      Student(
        id: '15',
        name: 'Trương Gia Linh',
        studentCode: 'SV2024015',
        className: 'CNTT-K21A',
        department: 'CNTT',
        major: 'IoT',
        course: 'K21',
        email: 'gialinh@univ.edu.vn',
        phone: '0901001015',
        address: 'Củ Chi, TP.HCM',
        birthDate: DateTime(2007, 1, 9),
        gender: Gender.female,
        gpa: 3.74,
        avatarUrl: 'https://i.pravatar.cc/150?img=21',
      ),
      Student(
        id: '16',
        name: 'Nguyễn Đức Mạnh',
        studentCode: 'SV2024016',
        className: 'KTQT-K21A',
        department: 'Kinh Tế',
        major: 'Tài chính ngân hàng',
        course: 'K21',
        email: 'ducmanh@univ.edu.vn',
        phone: '0901001016',
        address: 'Hóc Môn, TP.HCM',
        birthDate: DateTime(2007, 3, 6),
        gender: Gender.male,
        gpa: 3.01,
      ),
      Student(
        id: '17',
        name: 'Lương Thu Uyên',
        studentCode: 'SV2024017',
        className: 'CNTT-K21B',
        department: 'CNTT',
        major: 'Thiết kế game',
        course: 'K21',
        email: 'thuyen@univ.edu.vn',
        phone: '0901001017',
        address: 'Bình Chánh, TP.HCM',
        birthDate: DateTime(2007, 5, 19),
        gender: Gender.female,
        gpa: 2.81,
      ),
      Student(
        id: '18',
        name: 'Kiều Anh Dũng',
        studentCode: 'SV2024018',
        className: 'QTKD-K21B',
        department: 'Kinh Tế',
        major: 'Logistics',
        course: 'K21',
        email: 'anhdung@univ.edu.vn',
        phone: '0901001018',
        address: 'Quận 12, TP.HCM',
        birthDate: DateTime(2007, 10, 8),
        gender: Gender.male,
        gpa: 3.39,
        avatarUrl: 'https://i.pravatar.cc/150?img=8',
      ),
    ];
  }
}
