// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrnC9ko_l7YJ6HEUmdHK6k3fCHiH-oZw0',
    appId: '1:1024315521379:web:10f3fe26e30b78c5e5bb56',
    messagingSenderId: '1024315521379',
    projectId: 'studentmanager-7a3b5',
    authDomain: 'studentmanager-7a3b5.firebaseapp.com',
    storageBucket: 'studentmanager-7a3b5.firebasestorage.app',
    measurementId: 'G-F05E5Q3KQR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnWZhIJLjgLpXMLoY46KRyV7bTkzq87ig',
    appId: '1:1024315521379:android:88d93c8cb02da66be5bb56',
    messagingSenderId: '1024315521379',
    projectId: 'studentmanager-7a3b5',
    storageBucket: 'studentmanager-7a3b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOxm9KnxB_akPD52KMuIz7vBM8AoTxmtM',
    appId: '1:1024315521379:ios:0706e61289362320e5bb56',
    messagingSenderId: '1024315521379',
    projectId: 'studentmanager-7a3b5',
    storageBucket: 'studentmanager-7a3b5.firebasestorage.app',
    iosBundleId: 'com.example.studentManager',
  );
}
