// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo0yHS0xs-BmCfUbHLFj1plmluIBudvG8',
    appId: '1:1024315521379:web:10f3fe26e30b78c5e5bb56',
    messagingSenderId: '1024315521379',
    projectId: 'studentmanager-7a3b5',
    authDomain: 'studentmanager-7a3b5.firebaseapp.com',
    storageBucket: 'studentmanager-7a3b5.firebasestorage.app',
    measurementId: 'G-F05E5Q3KQR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDN8miYrOXklJXP9rmcG4ufNGXsR4VAHC0',
    appId: '1:1024315521379:android:88d93c8cb02da66be5bb56',
    messagingSenderId: '1024315521379',
    projectId: 'studentmanager-7a3b5',
    storageBucket: 'studentmanager-7a3b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOxm9KnxB_akPD52KMuIz7vBM8AoTxmtM',
    appId: '1:1024315521379:ios:0706e61289362320e5bb56',
    messagingSenderId: '1024315521379',
    projectId: 'studentmanager-7a3b5',
    storageBucket: 'studentmanager-7a3b5.firebasestorage.app',
    iosBundleId: 'com.example.studentManager',
  );

  // Desktop apps can use the same Firebase web app configuration.
  static const FirebaseOptions macos = web;
  static const FirebaseOptions windows = web;
  static const FirebaseOptions linux = web;
}
